#!/usr/bin/env python3
"""Build OpenWrt .apk packages (apk-tools / Alpine **v2** format) without the SDK.

!! 适用范围：OpenWrt 24.10（apk-tools 2.x）。
!! OpenWrt / ImmortalWrt 25.12 起是 apk-tools 3.x，只接受 APKv3 格式
!! （文件头 ADB 魔数的二进制 adb 格式），v2 包装不上，会报
!! "unexpected end of file"。25.12+ 请改用 tools/build_apk_on_router.sh，
!! 它会调用路由器自带的 `apk mkpkg` 生成 v3 包。

An unsigned apk v2 package is just two concatenated gzip streams:

    [ signature stream (omitted here) ]
    control.tar.gz   -> .PKGINFO
    data.tar.gz      -> the files to install

Both packages here are pure scripts (noarch, no compilation), so we can emit
them locally with plain CPython. Install with --allow-untrusted (no signature).

Usage:
    python3 tools/make_apk.py
    python3 tools/make_apk.py --outdir /tmp
"""

import argparse
import gzip
import hashlib
import io
import os
import sys
import tarfile
import time
import zlib

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def gzip_bytes(raw):
    out = io.BytesIO()
    with gzip.GzipFile(filename="", mode="wb", fileobj=out, mtime=0, compresslevel=9) as gz:
        gz.write(raw)
    return out.getvalue()


def _add_dir(tf, name):
    ti = tarfile.TarInfo(name)
    ti.type = tarfile.DIRTYPE
    ti.mode = 0o755
    ti.mtime = 0
    ti.uid = ti.gid = 0
    ti.uname = ti.gname = "root"
    tf.addfile(ti)


def tar_gz(items, dirs=()):
    """items: list of (arcname, bytes, mode); dirs: parent dirs to emit first.

    要点（对照 Alpine 官方 apk 实测得出）：
    - 官方数据段会带上父目录条目（0755），这里照做
    - Python tarfile 默认把 tar 填充到 RECORDSIZE=10240，官方包没有这段填充，
      必须裁掉，只保留 512*2 的结束标记
    """
    raw = io.BytesIO()
    with tarfile.open(fileobj=raw, mode="w", format=tarfile.USTAR_FORMAT) as tf:
        for d in dirs:
            _add_dir(tf, d)
        for name, data, mode in items:
            ti = tarfile.TarInfo(name)
            ti.type = tarfile.REGTYPE
            ti.size = len(data)
            ti.mode = mode
            ti.mtime = 0
            ti.uid = ti.gid = 0
            ti.uname = ti.gname = "root"
            tf.addfile(ti, io.BytesIO(data))

    buf = raw.getvalue()
    # 裁掉 RECORDSIZE 填充，只保留 tar 结束标记（两个 512 全零块）
    end = len(buf)
    while end > 0 and buf[end - 1] == 0:
        end -= 1
    end += (-end) % 512
    return gzip_bytes(buf[:end] + b"\0" * 1024)


def parent_dirs(arcname):
    """'a/b/c.sh' -> ['a', 'a/b']"""
    parts = arcname.split("/")[:-1]
    out = []
    for i in range(len(parts)):
        out.append("/".join(parts[: i + 1]))
    return out


def read(path):
    with open(path, "rb") as fh:
        return fh.read()


def build_apk(name, version, pkgdesc, files, depend, outdir, origin=None):
    """files: list of (source_path, arcname, mode)"""
    missing = [s for s, _, _ in files if not os.path.isfile(s)]
    if missing:
        print("  ! missing source files: %s" % ", ".join(missing), file=sys.stderr)
        return None

    data_items = [(arc, read(src), mode) for src, arc, mode in files]
    dirs = []
    for _, arc, _ in files:
        for d in parent_dirs(arc):
            if d not in dirs:
                dirs.append(d)
    data_seg = tar_gz(data_items, dirs=dirs)

    installed_size = sum(len(d) for _, d, _ in data_items)
    datahash = hashlib.sha256(data_seg).hexdigest()

    pkginfo = "\n".join(
        [
            "# Generated by tools/make_apk.py",
            "# %s" % time.strftime("%a %b %d %H:%M:%S %Y", time.gmtime(0)),
            "pkgname = %s" % name,
            "pkgver = %s" % version,
            "arch = noarch",
            "size = %d" % installed_size,
            "origin = %s" % (origin or name),
            "pkgdesc = %s" % pkgdesc,
            "url = https://github.com/openwrt/packages",
            "builddate = %d" % int(time.time()),
            "packager = make_apk.py",
            "license = GPL-2.0-or-later",
            "maintainer = David Yang <mmyangfl@gmail.com>",
        ]
        + ["depend = %s" % d for d in depend]
        + ["datahash = %s" % datahash, ""]
    ).encode("utf-8")

    control_seg = tar_gz([(".PKGINFO", pkginfo, 0o644)])
    apk = control_seg + data_seg

    os.makedirs(outdir, exist_ok=True)
    path = os.path.join(outdir, "%s-%s.apk" % (name, version))
    with open(path, "wb") as fh:
        fh.write(apk)
    print("  -> %s (%d bytes, datahash %s...)" % (path, len(apk), datahash[:12]))
    return path


def split_streams(data):
    """Split concatenated gzip streams.

    Returns (decompressed_segments, raw_segments) where raw_segments holds the
    original compressed byte ranges, so datahash can be checked against the real
    bytes instead of a re-compressed copy.
    """
    dec, raw, pos = [], [], 0
    while pos < len(data):
        d = zlib.decompressobj(16 + zlib.MAX_WBITS)
        buf = d.decompress(data[pos:])
        consumed = len(data) - pos - len(d.unused_data)
        if consumed <= 0:
            break
        dec.append(buf)
        raw.append(data[pos:pos + consumed])
        pos += consumed
        if not d.unused_data:
            break
    return dec, raw


def verify(path):
    """Re-parse a produced .apk and check structure / datahash."""
    data = open(path, "rb").read()
    streams, raw = split_streams(data)
    ok = True
    print("  verifying %s" % os.path.basename(path))
    if len(streams) != 2:
        print("    [FAIL] 期望 2 个 gzip 段(控制+数据)，实际 %d" % len(streams))
        ok = False
        return ok
    ctrl = tarfile.open(fileobj=io.BytesIO(streams[0]))
    names = ctrl.getnames()
    if ".PKGINFO" not in names:
        print("    [FAIL] 控制段缺少 .PKGINFO，实际: %s" % names)
        ok = False
    else:
        info = ctrl.extractfile(".PKGINFO").read().decode()
        print("    [OK] .PKGINFO 存在，%d 行" % len(info.splitlines()))
        for key in ("pkgname", "pkgver", "arch", "size", "datahash"):
            if ("%s = " % key) in info:
                print("    [OK] 含 %s" % key)
            else:
                print("    [FAIL] 缺少 %s" % key)
                ok = False
        declared = [l.split("=", 1)[1].strip() for l in info.splitlines() if l.startswith("datahash")]
        if declared:
            actual = hashlib.sha256(raw[1]).hexdigest()
            if actual == declared[0]:
                print("    [OK] datahash 与真实数据段一致 (%s...)" % actual[:16])
            else:
                print("    [FAIL] datahash 不匹配: 声明 %s 实际 %s" % (declared[0], actual))
                ok = False
    files = tarfile.open(fileobj=io.BytesIO(streams[1])).getmembers()
    for m in files:
        print("    [OK] 数据段: %s (mode %s)" % (m.name, oct(m.mode)))
    return ok


def _retar(decompressed):
    """Re-wrap a tar buffer into a fresh gzip stream (same bytes as打包时)."""
    return decompressed


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--outdir", default=os.path.join(REPO, "apk"))
    ap.add_argument("--version", default="5", help="version of ieee8021xclient")
    args = ap.parse_args()

    print("Building apk packages into %s" % args.outdir)

    paths = []
    paths.append(
        build_apk(
            name="ieee8021xclient",
            version="%s-r0" % args.version,
            pkgdesc="Wired 802.1x client config support in /etc/config/network",
            files=[
                (
                    os.path.join(REPO, "net/ieee8021xclient/files/ieee8021xclient.sh"),
                    "lib/netifd/proto/ieee8021xclient.sh",
                    0o755,
                )
            ],
            # 上游是 @(PACKAGE_wpa-supplicant||PACKAGE_wpad) 的构建期选择，apk 无 OR 依赖，
            # 因此不强拉依赖，请先确认设备已装 wpad 或 wpa-supplicant
            depend=[],
            outdir=args.outdir,
        )
    )
    paths.append(
        build_apk(
            name="luci-proto-ieee8021xclient",
            version="1-r0",
            pkgdesc="LuCI support for the wired IEEE 802.1X client protocol",
            files=[
                (
                    os.path.join(
                        REPO,
                        "luci-proto-ieee8021xclient/htdocs/luci-static/resources/protocol/ieee8021xclient.js",
                    ),
                    "www/luci-static/resources/protocol/ieee8021xclient.js",
                    0o644,
                )
            ],
            depend=["ieee8021xclient"],
            outdir=args.outdir,
        )
    )

    print()
    allok = True
    for p in paths:
        if p:
            allok = verify(p) and allok

    print("\nInstall on the router (OpenWrt 24.10+ / apk):")
    print("  scp %s/*.apk root@router:/tmp/" % args.outdir)
    print("  ssh root@router 'apk add --allow-untrusted /tmp/*.apk'")
    print("  ssh root@router 'service network restart; rm -f /tmp/luci-indexcache*'")
    print("\n验证结果: %s" % ("全部通过" if allok else "有失败项"))
    return 0 if allok else 1


if __name__ == "__main__":
    sys.exit(main())
